### ISSUE TITLE
See if compiletest can be turned into a cargo subcommand

### ISSUE THREAD

**Issue by laumann** [laumann/compiletest-rs#10]
See https://github.com/rust-lang/cargo/wiki/Third-party-cargo-subcommands

**Comment by Munksgaard** [comment]
What would that enable us to do that `cargo test` doesn't?

**Comment by laumann** [comment]
Initially I figured it would make it more obvious that it is not the standard test suite being run (where the user might have certain expectations as to what happens) - as it is, we're kind of abusing the test framework to run the compiletest tool.

But as I think more about it, providing a subcommand would allow us to expose the configuration options as command-line flags, so we should be able to offer options to add paths to the search path, run only specific modes and even just run specific tests. At the moment these options have to be programmatically configured.

On the bonus side, one method does not exclude the other one - you could use the compiletest tool and have it run with `cargo test`, and also have the `compiletest` subcommand.

**Comment by laumann** [comment]
This could be done as a separate project, so I'll close it here See [here](https://github.com/laumann/cargo-compiletest)
