### ISSUE TITLE
Unable to use "pretty" tests

### ISSUE THREAD

**Issue by denzp** [laumann/compiletest-rs#111]
Tests with `Mode::Pretty` aren't currently working because:
```
error: pretty-printing failed in round 0 revision None
status: exit code: 101
command: "rustc" "-" "-Zunstable-options" "--unpretty" "expanded" "--target" "x86_64-unknown-linux-gnu" "-L" "/tmp/target-attr.stage-id.pretty.aux" "-L" "crate=../target/debug/" "-L" "dependency=../target/debug/deps/"

stdout:
------------------------------------------
------------------------------------------

stderr:
------------------------------------------
error: Unrecognized option: 'unpretty'
------------------------------------------
```

It caused by changes in Rust [#47440](https://github.com/rust-lang/rust/pull/47440).
Instead of `-Zunstable-options --unpretty TYPE` we need to use `-Z unpretty=TYPE`.

Should it be enough just to propagate [the changes](https://github.com/rust-lang/rust/pull/47440/files#diff-442d7ffcafff5c5246d8c6c287fd5683R469) here?

**Comment by laumann** [comment]
Hi! Thanks for reporting this. Yeah, usually just propagating the changes should work.

In this case, it might make sense to also extend the test-project with a pretty mode test, so ensure it keeps working.
