### ISSUE TITLE
Support running tests in parallel

### ISSUE THREAD

**Issue by RalfJung** [laumann/compiletest-rs#117]
It would be great if compiletest was able to run mutliple tests in parallel - e.g. when there are 80 run-pass tests, it should run several of them in parallel to speed up testing.

From what I am told, rustc does something like that already. So maybe all it takes is updating compiletest from rustc?

**Comment by laumann** [comment]
Could be, that would be something relatively new within compiletest, no? (I think the last alignment-with-rustc/compiletest was back is March.)

**Comment by RalfJung** [comment]
I don't know, I haven't found the source of parallelism in rustc yet.  But there are now comments like
```
        // Incremental tests are special because they cannot be run in
        // parallel.
```

**Comment by RalfJung** [comment]
There seems to be something in libtest though: https://github.com/rust-lang/rust/blob/master/src/libtest/lib.rs#L898

**Comment by RalfJung** [comment]
Actually libtest does this automatically without any configuration. There is nothing to do, I just didn't know it was already happening... sorry for the noise!

**Comment by laumann** [comment]
Haha, no worries, thanks for enlighting me :-)
