### ISSUE TITLE
Stable build is broken: Could not find `RunIgnored` in `test`

### ISSUE THREAD

**Issue by dtolnay** [laumann/compiletest-rs#133]
```console
$ cargo +stable build --features stable
   Compiling compiletest_rs v0.3.14
error[E0433]: failed to resolve. Could not find `RunIgnored` in `test`
   --> src/lib.rs:101:52
    |
101 |         run_ignored: if config.run_ignored { test::RunIgnored::Yes } else { test::RunIgnored::No },
    |                                                    ^^^^^^^^^^ Could not find `RunIgnored` in `test`

error[E0433]: failed to resolve. Could not find `RunIgnored` in `test`
   --> src/lib.rs:101:83
    |
101 |         run_ignored: if config.run_ignored { test::RunIgnored::Yes } else { test::RunIgnored::No },
    |                                                                                   ^^^^^^^^^^ Could not find `RunIgnored` in `test`
```

**Comment by dtolnay** [comment]
Could you please yank 0.3.15 until this is fixed? I would like to prioritize keeping the stable build working over having nightly working.

**Comment by laumann** [comment]
Dang, this stable support is becoming a pain in the neck tbh :-/ I'll yank it.

**Comment by laumann** [comment]
Ok, yanked.

**Comment by dtolnay** [comment]
Thanks. I suspect that you are looking at this wrong: the stable support is dead simple -- just don't break anything. The nightly support is a pain in the neck. I filed https://github.com/laumann/compiletest-rs/issues/135 to follow up.

**Comment by Manishearth** [comment]
Clippy (and miri?) _must_ test on nightly, please don't break nightly support. Stable crates can still test on nightly, the other way around doesn't work.

**Comment by laumann** [comment]
> Thanks. I suspect that you are looking at this wrong: the stable support is dead simple -- just don't break anything.

The way I see, the stable support is an added feature. It's definitely not a feature in rustc/compiletest. It was added because it was relatively simple to do at the time, but it's becoming more of a burden to maintain. Nightly support is simply just keeping up with rustc/compiletest. Fx the changes in #136 will have to be undone/changed when stable catches up to nightly (if I understand correctly). That's what I meant by pain in the neck :-)

But don't get me wrong, I'm happy to know that people use it! Both stable AND nightly :-)

**Comment by dtolnay** [comment]
I believe compiletest-rs would deliver a better experience if there weren't unstable code enabled by default.

**Comment by laumann** [comment]
[0.3.16](https://crates.io/crates/compiletest_rs/0.3.16) is out.

**Comment by RalfJung** [comment]
@laumann thanks!

**Comment by dtolnay** [comment]
@SergioBenitez that's what I would like to see. Tracked in https://github.com/laumann/compiletest-rs/issues/135.
