### ISSUE TITLE
Make "stable" the default, require Cargo feature to opt in to pretty-printer support

### ISSUE THREAD

**Issue by dtolnay** [laumann/compiletest-rs#135]
Currently the only nightly-only functionality that you lose with `features = ["stable"]` is support for pretty-printing tests. In my experience practically nobody outside of the compiler uses this type of test. It's a shame to be chained to the nightly treadmill by default just for supporting that type of test.

It would be much nicer to have compiletest-rs work equally well on stable and nightly by default, and require an opt-in in the rare case that somebody requires nightly-only pretty printer tests.

If, as I expect, nobody enables the pretty-printing test support, then compiletest-rs would never again be broken by nightly changes.

**Comment by Manishearth** [comment]
Wait, where is this used for pretty tests? It seems to only be used for setting the host/target platforms?

**Comment by dtolnay** [comment]
https://github.com/laumann/compiletest-rs/blob/4b6b7c7e62981ba53e176d6a314167eafff7aec2/src/runtest.rs#L267-L273

---

I am not counting:

https://github.com/laumann/compiletest-rs/blob/4b6b7c7e62981ba53e176d6a314167eafff7aec2/src/common.rs#L347-L354

because in my experience the norustc version of that code works just as well as the unstable one. Has that not been your experience?

**Comment by Manishearth** [comment]
oh, I didn't think to grep for the "stable" feature itself.

nah, that was just the only nightly-specific code I found

**Comment by shepmaster** [comment]
Additionally, since features are supposed to be *additive*, it seems incorrect that `stable` is a feature — the logic should be negated.
