### ISSUE TITLE
Feature request: Expand macros

### ISSUE THREAD

**Issue by jeremydavis519** [laumann/compiletest-rs#145]
I'm working on a crate that makes a `functionlike!` procedural macro. I'd like to be able to test cases in which it should fail to expand because of a syntax error somewhere in its arguments, but it looks like compiletest_rs just sees a macro invocation and assumes it'll be fine. I wrote a test case for every possible kind of syntax error, but because everything outside the macro's fine, the `compile-fail` tests are failing. The test cases all look roughly like this:

```rust
fn test_case() {
    macro_name! {
        code with syntax errors
    }
}
```

I have a workaround in mind, but it would be nice to be able to do this in a standard way.

**Comment by SergioBenitez** [comment]
You can do exactly what you're proposing with `compiletest`. The library just calls `rustc` and gets the error output. It isn't responsible for (or not) expanding macros. `rustc`, of course, does expand, typecheck, and compile the expansion of macros. If there's an error, you'll see it and be able to check for it. This is exclusively what [Rocket uses compiletest for](https://github.com/SergioBenitez/Rocket/tree/master/core/codegen/tests/ui-fail) in checking its procedural macros, derives, and attributes, for instance.
