### ISSUE TITLE
The 0.3.24 crate version includes changes not present in the master branch

### ISSUE THREAD

**Issue by jakubadamw** [laumann/compiletest-rs#190]
```sh
$ curl -L 'https://crates.io/api/v1/crates/compiletest_rs/0.3.24/download' | tar -zxf
$ sed '262q;d' compiletest_rs-0.3.24/src/lib.rs
            test_type: test::TestType::IntegrationTest,
```

https://github.com/laumann/compiletest-rs/blob/71c27439a440c6c0fdb5a30feadea1fc76d50264/src/lib.rs#L262

https://github.com/laumann/compiletest-rs/blob/master/Cargo.toml#L3

Or perhaps I am missing something?

I am seeing build failures without `features = ["stable"]` on the latest nightly and I wanted to report it properly. However, it looks like the repository is out of sync with the crate anyway, so I decided to file an issue about it first.

**Comment by Manishearth** [comment]
I forgot to push, sorry.

The crate was fixed for rustc master, so you should wait till the next nightly (should be out now)
