### ISSUE TITLE
Tag releases 0.3.20 through 0.3.24 in master

### ISSUE THREAD

**Issue by laumann** [laumann/compiletest-rs#194]
If you look [here](https://github.com/laumann/compiletest-rs/releases) I got in the habit of tagging every version release (and actually writing out what changed and who contributed). This was actually requested in #71, but since 0.3.19 no new tags have been created.

Version | Released | Rev (guess)
------- | -------- | ---
[0.3.24](https://crates.io/crates/compiletest_rs/0.3.24) | Oct 13 | b3d5dd2d5727107058666ec16545d7e20637504b
[0.3.23](https://crates.io/crates/compiletest_rs/0.3.23) | Sep 25 |  179866199cdc89fe7910b25ab15e981b0b064b99
[0.3.22](https://crates.io/crates/compiletest_rs/0.3.22) | Apr 19 | ef3d8d5333e1de4826ffc9ca60f21909203c7fb5
[0.3.21](https://crates.io/crates/compiletest_rs/0.3.21) | Apr 7 | 913d01de1a45dd0913811d62b5d48b4fa64b5074
[0.3.20](https://crates.io/crates/compiletest_rs/0.3.20) | Mar 19 | 64ecab27021b49b1286577a8d54323819273d611

@Manishearth I figure you've been publishing the last six releases, can you confirm the hashes are the ones that need to be tagged? If so, just let me know and I'll tag them (or tag them yourself).

I would like keep the version bumps in separate commits because it makes it really easy to find in the history, so in future PRs I would ask that version bumps in Cargo.toml be removed.

When publishing a new version, _then_ you bump Cargo.toml, tag it and do the whole release dance.

Without the tags, we can only rely on the person who published the version to remember exactly _which_ revision was actually published.

**Comment by Manishearth** [comment]
@laumann yes, these look fine. in the future I'll ensure we do version bumps separately and with tags.

**Comment by Munksgaard** [comment]
I've gone ahead and tagged these releases, including bumping the version to 0.3.25 and tagging that. Do you think we should write some release notes as well, @laumann?

**Comment by laumann** [comment]
I usually do that, it's always nice to give credit to people who contributed to the releases.

**Comment by laumann** [comment]
@Manishearth Thanks.

**Comment by laumann** [comment]
@Munksgaard And thanks to you as well!

**Comment by Munksgaard** [comment]
@laumann Nope, I got @Manishearth to do it, because I'm not authorized yet.

**Comment by laumann** [comment]
> @laumann Nope, I got @Manishearth to do it, because I'm not authorized yet.

Alright, do you want me to add you?

**Comment by Munksgaard** [comment]
> Alright, do you want me to add you?

Yes, thank you, that would be nice. :+1:

**Comment by Manishearth** [comment]
Yeah I just assumed you had access lol
