### ISSUE TITLE
Feature request: Inline code to test

### ISSUE THREAD

**Issue by llogiq** [laumann/compiletest-rs#2]
My compile-fail directory is full of code snippets that contain the same lines (with one variation to exercise multiple failures) over and over.

To reduce clutter, it would be nice if we could define a prefix + suffix and a slice of code strings and pipe prefix + code + suffix into rustc instead of requiring specific files.

**Comment by laumann** [comment]
This is very typical of test, especially unit tests. Defining prefixes and suffixes reduces the independence of a single test - if you make changes to, say, the prefix, all the tests depending on that prefix might change their behaviour (in non-obvious ways). Although this is a tempting feature, I consider it an anti-pattern to a certain degree. Repetition is usually bad, but in testing you want isolated bits of code, and to me it is all about defining the proper boundaries between what can be shared and what must be its own unit.

But maybe this could be addressed using the macro system?

The tool offers quite a bit of configuration (that is admittedly not very well documented) and the config has an `aux_base` you can set for auxiliary libraries. Here's an example:

Create a folder alongside your compile-fail folder (I call it `auxiliary`), and
add;

```rust
// File: tests/auxiliary/aux.rs
#![crate_type = "rlib"]

// ... contents of crate
``` 

Make sure compiletest can find the directory by setting the `aux_base` path:

```rust
// File: tests/tests.rs
fn run_mode(mode: &'static str) {
    let mut config = compiletest::default_config();

    // ... other configuration
    config.aux_base = PathBuf::from(format!("tests/auxiliary"));

    compiletest::run_tests(&config);
}
```

And indicate in the tests that they want that particular crate built:

```rust
// File: tests/run-pass/impl-aux.rs
// aux-build:aux.rs
extern crate aux

// .. Rest of test file using crate 'aux'
```

**Comment by llogiq** [comment]
In my case, I want to test that my lint catches an expression, so my prefix and suffix would be

    #!feature(plugin)
    #!plugin(whatever_my_lint_is)
    #deny(my_lint)
    fn main() {

and

    }

But you're probably right, the duplication is not too bad, considering I can put multiple errors into one test file.
