### ISSUE TITLE
Adding `bless` support

### ISSUE THREAD

**Issue by phansch** [laumann/compiletest-rs#228]
Would there be any reason not to include the `bless` support from the rustc version of compiletest?

This seems to be useful for both miri and Clippy:

* https://github.com/rust-lang/miri/issues/1588
* https://github.com/rust-lang/rust-clippy/issues/5394

I'd be happy to try and copy the feature over, if there's nothing speaking against that.

**Comment by Manishearth** [comment]
I'd be happy to accept it.

Ideally we can uplift libtest and libcompiletest out of tree into crates so that clippy can just use the same one rustc does

**Comment by Munksgaard** [comment]
Closed by #231
