### ISSUE TITLE
How to handle conditional compilation?

### ISSUE THREAD

**Issue by Robzz** [laumann/compiletest-rs#25]
I'm currently writing a compile-fail test, with the following code in it : 
```rust
#[cfg(target_pointer_width = "64")]
    fn check_64() {
        let is : isize = -42;
        let us : usize = 42;
        is as f32; //~ERROR converting from isize to f32, which causes a loss of precision (isize is 64 bits wide, but f32's mantissa is only 23 bits wide)
        us as u32; //~ERROR casting usize to u32 may cause truncation of the value
        us as u64; // Should not trigger any lint
    }
#[cfg(target_pointer_width = "32")]
    fn check_32() {
        let is : isize = -42;
        let us : usize = 42;
        is as f32; //~ERROR converting from isize to f32, which causes a loss of precision (isize is 32 bits wide, but f32's mantissa is only 23 bits wide)
        us as u32; // Should not trigger any lint
        us as u64; // Should not trigger any lint
    }
```
This is part of the test case for a lint I'm writing for [rust-clippy](https://github.com/Manishearth/rust-clippy). Maybe this is misuse on my part (though I tried to make sure it isn't), but on my 64bit machine which only builds the `check_64` function, the compile-fail test fails because no error is generated in the body of `check_32`, which is normal since it is not compiled. Here is the exact message :
```
---- [compile-fail] compile-fail/cast.rs stdout ----
error: expected error on line 52 not found: converting from isize to f32, which causes a loss of precision (isize is 32 bits wide, but f32's mantissa is only 23 bits wide)
status: exit code: 101
command: rustc tests/compile-fail/cast.rs -L /tmp --target=x86_64-unknown-linux-gnu -L /tmp/cast.stage3libaux -C prefer-dynamic -o /tmp/cast.stage3 -L target/debug/
```
Is there any way to overcome this?

**Comment by Manishearth** [comment]
I don't think there's any way to do this. You could write two files and put `ignore-*` directives on them, but from scanning the tests in rustc there's no way to ignore a pointer width specification.

**Comment by laumann** [comment]
I think Manishearth is right - compiletest extracts the `~ERROR` markers before the file is compiled AFAIK and doesn't take conditional compilation into account. I think the proper way to do this is separate files as suggested with ignore directives.

**Comment by Robzz** [comment]
Okay, well the good news is that what I did was not the best thing to do, so it turns out I won't need the feature :)
Anyway that's good to know, thanks to both of you for your replies. Closing.
