### ISSUE TITLE
Test that the error position is good

### ISSUE THREAD

**Issue by antoyo** [laumann/compiletest-rs#29]
Hello.
Is it possible to test that a specific error is at the specified position.
For instance, I would like to be able to write something like:

```
// error-pattern: 14:13: 14:20 error: use of unsupported type name `&'a str` [E0412]
```

instead of:

```
// error-pattern: error: use of unsupported type name `&'a str` [E0412]
```

But it does not work.
Is there a way to do this?

If not, it would be very useful to test compiler plugins or lints that span a lot of errors to ensure that the errors are at the expected position.

Thanks.

**Comment by Manishearth** [comment]
You don't use error-pattern, you use `//~ERROR` on the specific line in that case.

**Comment by Manishearth** [comment]
See https://github.com/rust-lang/rust/tree/master/src/test/compile-fail for more examples of what  can be done.

**Comment by antoyo** [comment]
The `//~ERROR` pattern only checks the line, not the columns, which is what I want to test.

Is there any way of doing this?

**Comment by Manishearth** [comment]
No, sorry. (And this is just a port of the in-tree compiletest, major changes should be proposed there)

What you can do is split the expression across multiple lines to get the same effect.
