### ISSUE TITLE
Errors happening inside macro expansions

### ISSUE THREAD

**Issue by aldanor** [laumann/compiletest-rs#31]
Let's say I have a complex macro in a library which I want to test, and it fails within macro expansion (i.e., the macro expands fine, but there's a compile error which points inside macro). I get errors like this:

```sh
stderr:
------------------------------------------
<pod_typeinfo macros>:6:48: 6:52 error: the trait `Copy` may not be implemented for this type; field `a` does not implement `Copy` [E0204]
<pod_typeinfo macros>:6 # [ allow ( dead_code ) ] # [ derive ( Clone , Copy ) ] $ ( # [ $ attr ] ) *
                                                                       ^~~~
<pod_typeinfo macros>:6:48: 6:52 note: in this expansion of #[derive_Copy] (defined in <pod_typeinfo macros>)
tests/compile-fail/derive-clone.rs:4:1: 8:2 note: in this expansion of def! (defined in <pod_typeinfo macros>)
<pod_typeinfo macros>:6:48: 6:52 help: run `rustc --explain E0204` to see a detailed explanation
error: aborting due to previous error
```

Is there any way to match these errors? Placing `//~ ERROR` at the invocation line doesn't seem to work as it only captures macro expansion failures...

And here's the test itself:

```rust
#[macro_use]
extern crate pod_typeinfo;

def! {
    struct Foo {
        a: String 
    }
}

fn main() {}
```

**Comment by TimNN** [comment]
I know the reply comes a bit late, but you can use `// error-pattern: [part of your error]` to match errors anywhere

**Comment by laumann** [comment]
@aldanor I'll assume that this is not a problem anymore, also given @TimNN's workaround. Feel free to re-open if this is still a problem.

**Comment by aldanor** [comment]
@laumann Yes, looks like that workaround helps in cases like this. Thanks!

**Comment by laumann** [comment]
Glad to hear it :smile:
