### ISSUE TITLE
Broken on windows msvc

### ISSUE THREAD

**Issue by oli-obk** [laumann/compiletest-rs#35]
[This line](https://github.com/laumann/compiletest-rs/blob/6ab43b302fe0bda2be7bdb285b6811d564ef4758/src/compiletest.rs#L53) sets the `build_base` to `/tmp`, which makes zero sense on windows. Maybe the default could be `target/debug` or a subdirectory of that?

**Comment by laumann** [comment]
Yeah, `tmp` is not useful on windows :smile: I'm surprised that line has survived this long - must not be many users on windows...

But you should be able to override it, just like the `mode` parameter:
```rust
let mut config = compiletest::default_config();
config.build_base = PathBuf::from("/some/other/dir");
```

The default config is meant just to give you a Config struct to tweak the settings, but in this case I can see that changing the default settings here would give it a broader applicability. Hardcoding this setting to a system-specific value also forces every single tester (who wants to run their tests  on various systems) to override it.

Is `target/debug` the best choice? Or should compiletest try to infer tmp directories on different systems?

**Comment by oli-obk** [comment]
I found something that works: https://doc.rust-lang.org/std/env/fn.temp_dir.html maybe just default to that?
