### ISSUE TITLE
Remove -rs from project & crate name

### ISSUE THREAD

**Issue by alexreg** [laumann/compiletest-rs#40]
i.e. It's okay for the repository name, but really shouldn't be in the project or crate name in the `Cargo.toml`.

**Comment by laumann** [comment]
I've been thinking about this. If I remember correctly, I opted for the _rs/-rs suffix, to avoid potential clashes. I also just remembered that `compiletest` is a reserved name on crates.io: https://github.com/rust-lang/crates.io/blob/master/src/reserved_crates.txt

I don't know if we can change the crate name to `compiletest` and still publish it on crates.io.

**Comment by alexreg** [comment]
You can’t definitely change the crate name just to `compiletest` (under the `lib` section in the `Cargo.toml`). Alternatively, you could change the project and crate name to `compile-test` (with the dash).

**Comment by laumann** [comment]
I'm not sure I understand the difference then, is there some reason that the `_rs` suffix should be avoided?

**Comment by laumann** [comment]
I asked on IRC, and the consensus seems to be that the `_rs` suffix just doesn't add anything, and had some alternative name suggestions
 - `compiletest-pub` / `compiletest-ext` (to reflect that it's a public version of rustc's compiletest)
 - `willitcompile` (thanks Yurume)
 - `compile-test` (suggested by @alexreg and Quuxy)

I originally wanted to keep the `compiletest` word in there to keep the association with rustc's version, but maybe that's not necessary.

@Manishearth Any thoughts?

**Comment by Munksgaard** [comment]
>  willitcompile (thanks Yurume)

I don't think that's a good suggestion, since `compiletest` is best at checking that certain programs _don't_ compile.

**Comment by Munksgaard** [comment]
I think it's preferable to keep a close association with rustc's `compiletest`. `compiletest-rs` is mostly just an extraction of the original tool with very little modification. I therefore prefer `compiletest-ext`, `compiletest-pub` or something similar.

Why couldn't we properly extract compiletest from rustc and separate it into it's own actual crate? Sort of like `rand` or `rustc-serialize` were extracted. I'm sure we considered this at some point, but I forgot why we couldn't do it.

**Comment by alexreg** [comment]
That sounds sensible to me. On both points.

**Comment by Manishearth** [comment]
I think the plan is eventually to publish compiletest (cc @jonathandturner), so I'm not sure if it's worth renaming it right now.

**Comment by alexreg** [comment]
"Eventually" means it's definitely worth it to me.

**Comment by laumann** [comment]
I'll close this. It's hasn't been discussed in over two years, so I would like to consider the debate over for the time being.
