### ISSUE TITLE
nixcrates fails to compile

### ISSUE THREAD

**Issue by laumann** [laumann/compiletest-rs#53]
I got the following request from @sjmackenzie:
> Hello,
> 
> If you could be so kind to follow rust convention and rename the
> default lib entry point to lib.rs for this file
> https://github.com/laumann/compiletest-rs/blob/master/Cargo.toml#L16
> 
> this library does not compile when using
> github.com/fractalide/nixcrates which looks for the default lib.rs but
> cannot find it.
> 
> kr/sjm

Should we let convention prevail here and just rename? Do we have any reason for keeping the lib entry point as `compiletest.rs`?

**Comment by sjmackenzie** [comment]
Thanks for your cooperation :-) I'm undertaking a herculean task of implementing a new package manager for rust+nix, it's github.com/fractalide/nixcrates and it provides a hermetically sealed build environment.

One major source of problems is folks not using the default entry point of lib.rs, this means knowledge of how to compile the crate is spread all over the place, when it doesn't have to be that way. It would be great if all crate authors follow the convention of lib.rs, ideally cargo fails the build. But this won't happen, so I'll have to create the mapping and manually edit myself. This won't be fun...

**Comment by laumann** [comment]
@Manishearth Any objections?
