### ISSUE TITLE
default config should include `host` from the current rustc

### ISSUE THREAD

**Issue by dwrensha** [laumann/compiletest-rs#65]
Miri's run-pass tests use a compiletest [default config without setting the `host` field](https://github.com/solson/miri/blob/f85c7a2c4d939efc26dcb60803c2393553f39c5c/tests/compiletest.rs#L21-L28). My expectation is that this would result in `host` and `target` being detected from the current version of rustc. Instead, `host` gets set to "(none)", which causes [a test that has `ignore-cross-compile`](https://github.com/solson/miri/blob/f85c7a2c4d939efc26dcb60803c2393553f39c5c/tests/run-pass/aux_test.rs#L2) to get unexpectedly ignored.

**Comment by dwrensha** [comment]
(cc @oli-obk @eddyb)

**Comment by oli-obk** [comment]
I've been wondering about that.

**Comment by laumann** [comment]
Would the change in #66 have any effect elsewhere?

**Comment by dwrensha** [comment]
I suppose someone could try running the change (#66) on the crates that depend on compiletest: https://crates.io/crates/compiletest_rs/reverse_dependencies --- something like a mini crater run. (cc @shepmaster, who I think at one point was wondering whether automation for such testing might be useful.)

I think the main things we should worry about are causing tests to fail silently and causing tests to be unexpectedly ignored. It seems unlikely to me that this change would result in either. Meanwhile, compiletest's current behavior is causing tests to be unexpectedly ignored right now out in the wild, as the miri code linked above shows.

**Comment by dwrensha** [comment]
c.f. https://github.com/laumann/compiletest-rs/pull/13, where the `target` field default behavior was added.

Why would the default have the `target` set from rustc, but have a "(none)" value in `host`?

**Comment by laumann** [comment]
I see your point wr #13 - I'll merge #66

**Comment by laumann** [comment]
https://crates.io/crates/compiletest_rs/0.2.7 is out!
