### ISSUE TITLE
No way to add multiple directories to library search path

### ISSUE THREAD

**Issue by doomrobo** [laumann/compiletest-rs#67]
Currently, there is only a single `-L` parameter given to `rustc` and it comes from the `config.build_base` variable. It would be nice to be able to have multiple inputs here. My specific use case is testing a procedural macro that's only defined on `struct`s. So my `compile-fail` needs to be able to pull in my library and one other dependency to make use of the procedural macro.

I found that the library search path info was available to the process via the `DYLD_LIBRARY_PATH`, but it contains multiple paths separated by colons. I tried passing this value wrapped in a `PathBuf` to the `config.build_base` variable, but I ended up with the error

```
---- [compile-fail] compile-fail/enum.rs stdout ----                                                                                                                                                                                thread '[compile-fail] compile-fail/enum.rs' panicked at 'called `Result::unwrap()` on an `Err` value: JoinPathsError { inner: JoinPathsError }', src/libcore/result.rs:860
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: <core::result::Result<T, E>>::unwrap
  10: compiletest_rs::procsrv::add_target_env
  11: compiletest_rs::procsrv::run
  12: compiletest_rs::runtest::TestCx::program_output
  13: compiletest_rs::runtest::TestCx::compose_and_run
  14: compiletest_rs::runtest::TestCx::compose_and_run_compiler
  15: compiletest_rs::runtest::TestCx::compile_test
  16: compiletest_rs::runtest::TestCx::run_cfail_test
  17: compiletest_rs::runtest::TestCx::run_revision
  18: compiletest_rs::runtest::run
  19: compiletest_rs::make_test_closure::{{closure}}
  20: <F as test::FnBox<T>>::call_box
  21: <F as test::FnBox<T>>::call_box
  22: __rust_maybe_catch_panic
```

So my hacky solution currently is to find the particular library search path that ends with `/deps` and then set `config.build_base` to that one.

```rust
let dyld_paths = env::var("DYLD_LIBRARY_PATH").unwrap();
for path in dyld_paths.split(":").map(PathBuf::from) {
    if path.ends_with("deps") {
        config.build_base = path;
    }
}
```

**Comment by laumann** [comment]
Yeah, that doesn't seem like a nice way to work with it...

Is there any reason for using `build_base` instead of `target_rustcflags`? The `build_base` seems to be where targets should be built and `target_rustcflags` is for adding more flags when calling rustc.

With `target_rustcflags` you should be able to do something like:
```
config.target_rustcflags = Some("-L target/debug".to_string());
```
and if you want multiple occurrences of `-L` you should be able to do:
```
config.target_rustcflags = Some("-L path/to/lib1 -L path/to/lib2".to_string());
```

**Comment by doomrobo** [comment]
Ah, I didn't notice that flag. But there's still the issue of picking the correct directory.

1. Can I be certain that this relative path will always be correct?
2. I still have to determine whether I'm in `debug` or `release` mode before picking the path

**Comment by laumann** [comment]
Hmm, I'm not sure - the relative path of course only works if you invoke `cargo build` from the right directory. I wonder how/if the paths could be converted to absolute paths?

As for (2) I'm not sure how to do that - `compiletest` does not receive information from Cargo, so I'm not sure how to provide that. Is this the kind of thing `build.rs` could be used for? Or could you have some method in the test runner that determines what type of build it is?

**Comment by doomrobo** [comment]
Having dumped all env vars, the only one that indicates the release target is `DYLD_LIBRARY_PATH`. So I guess this is the next best solution:

```rust
let dyld_paths = env::var("DYLD_LIBRARY_PATH").unwrap();
let mut compiler_flags = String::new();
for p in dyld_paths.split(":") {
    compiler_flags += &*format!(" -L {}", p);
}
config.target_rustcflags = Some(compiler_flags);
```

I guess this fixes my issue. Thanks!

**Comment by laumann** [comment]
np :smile:

Do you think the documentation needs some improvement to help with this sort of thing?

**Comment by doomrobo** [comment]
Absolutely. I'm used to having my dependencies available in all testing code, since that's cargo's default behavior. In fact, do you think it'd make sense to set these flags by default? If not, I'd still be happy to submit a PR later to add some docs for this issue.

**Comment by laumann** [comment]
That sounds sensible. The standard use case AFAIK is to set `-L target/debug` in rustc flags. I think we decided not to provide anything by default, because the user's requirement might be different.

I'd be happy to receive a PR with some improved docs.
