### ISSUE TITLE
Please add tags matching crates.io versions

### ISSUE THREAD

**Issue by RalfJung** [laumann/compiletest-rs#71]
Right now, it seems impossible to match crates.io releases with the git repository?

**Comment by laumann** [comment]
Will do, thanks for the suggestion.

**Comment by laumann** [comment]
@RalfJung I added tags for 0.2.9 back to 0.2.4 - is there a particular version you're looking for?

**Comment by RalfJung** [comment]
I was looking for the diff between 0.2.8 and 0.2.9. 0.2.8 is stated in the commit message, but also having it as a tag makes it stand out better.

**Comment by laumann** [comment]
Ok. I messed up some of the tags, so I'll be renaming them - if you already pulled them, please delete and pull them again...

**Comment by laumann** [comment]
I'll close this - I added tags all the way back to v0.1.0. Thanks again!
