### ISSUE TITLE
Default value of build_base leads to races when running tests concurrently

### ISSUE THREAD

**Issue by RalfJung** [laumann/compiletest-rs#72]
In [miri](https://github.com/solson/miri), we use compiletest in multiple `#[test]` functions, so they are executed in parallel. We see a lot of test failures like
```
error: compilation failed!

status: exit code: 101

command: target/release/miri tests/run-pass/aux_test.rs -L /tmp --target=x86_64-unknown-linux-gnu -Z dump-mir=all -Z mir-opt-level=3 -Z dump-mir-dir=/tmp/aux_test -L /tmp/aux_test.stage-id.mir-opt.libaux -C prefer-dynamic -o /tmp/aux_test.stage-id -Zmir-opt-level=0 -Zmir-emit-validate=1

stdout:

------------------------------------------

------------------------------------------

stderr:

------------------------------------------

error: linking with `cc` failed: exit code: 1

  |

  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/travis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/tmp/aux_test.0.o" "-o" "/tmp/aux_test.stage-id" "/tmp/aux_test.crate.allocator.o" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs" "-L" "/tmp" "-L" "/tmp/aux_test.stage-id.mir-opt.libaux" "-L" "/home/travis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-L" "/tmp/aux_test.stage-id.mir-opt.libaux" "-l" "dep" "-L" "/home/travis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "std-ab8512bb715ab82f" "-Wl,-Bstatic" "/home/travis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-53095306c4bf2e4a.rlib" "-Wl,-Bdynamic" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "pthread" "-l" "gcc_s" "-l" "c" "-l" "m" "-l" "rt" "-l" "pthread" "-l" "util"

  = note: /usr/bin/ld: cannot find /tmp/aux_test.0.o: No such file or directory

          /usr/bin/ld: cannot find /tmp/aux_test.crate.allocator.o: No such file or directory

          collect2: ld returned 1 exit status
```

From the behavior of the bug (it only occurs spuriously), this feels a lot like a race condition.
(It also shows that compiletest messes with `/tmp` really badly, rather than creating its own subdirectory, which I would have expected.)

We track this in miri as https://github.com/solson/miri/issues/305

**Comment by RalfJung** [comment]
Ah, I think I found it. The default value for `build_dir` is not chosen very well; it's always `/tmp`. For miri, we will use the tempdir crate to fix that, but I think the default could be better -- or at least, better documented (read: mentioned at all in [the docs](https://docs.rs/compiletest_rs/0.2.9/compiletest_rs/common/struct.Config.html)).

**Comment by laumann** [comment]
@RalfJung Thanks for reporting this. The `Config` struct is not documented well at all :-) it's a good comment to add to `build_dir`s documentation.

**Comment by laumann** [comment]
@RalfJung Just to be sure, you meant `build_base`, right?

**Comment by RalfJung** [comment]
Sorry, yes, I did.

**Comment by laumann** [comment]
No worries, thanks :smile: I submitted https://github.com/rust-lang/rust/pull/44126 to change the existing comments to doc comments.

**Comment by RalfJung** [comment]
Sounds like a good start!

How bad would it be for this crate to depend on tempfile? You could then provide a constructor that just does the right thing.

**Comment by laumann** [comment]
Hmm, could it be added as an opt-in feature somehow? That would be awesome.

**Comment by RalfJung** [comment]
Yeah, cargo features can totally do that.
