### ISSUE TITLE
Incorrect folder name is printed for each test

### ISSUE THREAD

**Issue by RalfJung** [laumann/compiletest-rs#76]
In miri, we have a folder `compile-fail-fullmir` for compile-fail tests that need a different setup than those in compile-fail. This reveals that compiletest prints the wrong path to the file that it is testing:
```
## Running compile-fail tests in tests/compile-fail-fullmir against miri for target x86_64-unknown-linux-gnu

running 1 test
test [compile-fail] compile-fail/undefined_byte_read.rs ... ok
```
This says the file name is `compile-fail/undefined_byte_read.rs` while it really is `compile-fail-fullmir/undefined_byte_read.rs`. compiletest seems to use the suite name when printing the folder name, which is not in general correct.

I tried to fix this myself, but unfortunately I could not even find the place in the code that does this printing...

**Comment by RalfJung** [comment]
Ah, I think I found it -- in make_test_name.

**Comment by laumann** [comment]
That does seem to be a bug... The assumption is that the `config.mode` is also the name of the directory. Is `compile-fail-fullmir` available in `Config` somewhere?

**Comment by laumann** [comment]
Would it be `src_base`?

**Comment by RalfJung** [comment]
@laumann Yes it is in `src_base`. I am working on a PR for rustc.

**Comment by laumann** [comment]
Nice :-) Just submit a PR here as well, or ping me when it's in, then I'll replicate it here and release a new version

**Comment by laumann** [comment]
Looking at miri, you might want to update to compiletest 0.3.0 - it might cause some breakage though as the update changed the type of some fields in `Config`

**Comment by RalfJung** [comment]
Well I guess I'll see and fix that breakage as I update to the version that fixes this. ;)

**Comment by laumann** [comment]
Yeah ok :-) I was just thinking that 0.3.0 is much closer to the current rustc/compiletest, the 0.2 series was getting behind a bit.

**Comment by RalfJung** [comment]
The upstream rustc PR has been merged.

**Comment by laumann** [comment]
Nice!

**Comment by RalfJung** [comment]
Any chance of a release with this fix? :D

**Comment by laumann** [comment]
Yeah, sure thing :-)

**Comment by laumann** [comment]
[0.3.1](https://crates.io/crates/compiletest_rs/0.3.1) is out

**Comment by RalfJung** [comment]
Thanks, that was fast. :-)
