### ISSUE TITLE
[E0464]: multiple matching crates after using cargo check

### ISSUE THREAD

**Issue by hdhoang** [laumann/compiletest-rs#78]
Running `cargo check` creates a `.rmeta` file with a different hash than the actual rlib built. This makes `cargo test` unable to compile tests which import the tested crate for integration testing.

This travis build fails because of the duplicate files https://travis-ci.org/hdhoang/testee/jobs/285433441#L481
It runs fine after removing the `rmeta` file https://travis-ci.org/hdhoang/testee/builds/285434745#L443

This is possibly related to rust-lang/cargo#3501. Until `check` and `build` use the same metadata, this issue would hinder `compiletest-rs` adoption.

I think we can workaround this by removing the relevant rmeta files when building tests.

**Comment by laumann** [comment]
That does seem annoying... Could removal of the `*.rmeta` be done as part of the test initialization or is that too late? If it's too late, then I'm not sure this is fixable in compiletest. A feature of `Config` could be to clear out `*.rmeta` in build folders on request.

As a side question, why use `cargo check` for integration testing? Is it even necessary (to run tests, you'd have to run build at some point anyway).

**Comment by hdhoang** [comment]
Thank you for your pointer, I'll try that out.

I run `cargo check` during normal development, but it still creates the conflicting `*.rmeta` discovered from `tests/run-pass/*.rs`. Later, `cargo test` gets confused by those during actual testing.

**Comment by laumann** [comment]
> I run cargo check during normal development

Ah, I see. It's not the test suite that runs `cargo check`, sorry :-)
