### ISSUE TITLE
Test does not get compiled via `compiletest-rs`

### ISSUE THREAD

**Issue by fuine** [laumann/compiletest-rs#85]
I'm having troubles incorporating `compiletest` into `lazy_static` codebase - I have a simple setup but `compiletest` does not find any warnings/errors:
```
error: 0 unexpected errors found, 1 expected errors not found
status: exit code: 101
```
even though if I run the command printed out it works as expected - yields the expected error. Am I doing something wrong, or is it a problem with `compiletest`?
```
$ rustc --version
rustc 1.23.0-nightly (02004ef78 2017-11-08)
```
I can reproduce the same problems by simply running `cargo test` in the `test-project` directory of this crate.

**Comment by fuine** [comment]
Turns out i had some problems with macro expansion, as it changes line numbers, but I think that overall `0 unexpected errors` is quite misleading, as it indicates that the code does not yield any warnings/errors, while in fact it does. Moreover I think that allowing `dead_code` should be documented somewhere, because I found out about it by accident.

@laumann I will close this issue, but I think you should take above comments under consideration

**Comment by laumann** [comment]
@fuine Thanks for your report - sorry for not getting back sooner.

What was the macro expansion problem exactly? I'd like to understand it a bit better. There have been some issues with the `link_deps()` method that was introduced recently and paths with spaces (see #81), maybe it's related?
