### ISSUE TITLE
Request - Publish crate to crates.io

### ISSUE THREAD

**Issue by thepowersgang** [laumann/compiletest-rs#9]
I have pinged #cargo as a quick check, and there's no issue with publishing this crate.

Use case: I have a plugin that uses this crate to ensure it works, but can't publish with those tests active (becuase cargo requires all dependencies to be on crates.io before you can publish)

**Comment by laumann** [comment]
I'll get right on it :smile:

**Comment by laumann** [comment]
@thepowersgang it seems I'll be forced to change the name of the crate - `compiletest` is a reserved name: https://github.com/rust-lang/crates.io/blob/master/src/reserved_crates.txt

Any suggestions for a new name?
 - ctest
 - compiletestrs
 - rust_compiletest
 - petulant-lana
 - shiny-ironman
@Munksgaard @Manishearth Any suggestions?

**Comment by Manishearth** [comment]
I'd actually prefer `compiletest_rs`

I can publish this if you want; but I'll need access to the repo.

**Comment by laumann** [comment]
Ooops, hit the wrong button

**Comment by laumann** [comment]
Published here: https://crates.io/crates/compiletest_rs
@Manishearth Can I add you as owner as well?

**Comment by Manishearth** [comment]
\o/ Sure, feel free to add me as an owner :)

**Comment by laumann** [comment]
@llogiq @Munksgaard @thepowersgang I'm just letting you know the crate name has changed from `compiletest` to `compiletest_rs`, which is a breaking change.

The crate is also on crates.io now, so you could consider referencing that instead. If I'm not mistaken you should just add
```toml
[dev-dependencies]
compiletest_rs = "*"
```
to Cargo.toml

**Comment by llogiq** [comment]
Cool. Thank you.

**Comment by Munksgaard** [comment]
:+1:
