### ISSUE TITLE
Allows executing the tests with a runner

### ISSUE THREAD

**Issue by malbarbo** [laumann/compiletest-rs#92]
Consider reading the [cargo](https://github.com/rust-lang/cargo/pull/3954) [runner](http://doc.crates.io/config.html#configuration-keys) parameter or adding an alternative way to specify the test runner. This would allows testing cross compiled tests (for now, one must rely on binfmt).

**Comment by laumann** [comment]
If I understand the runner thing right, specifying something like "bash" or "python" would make cargo run those with the compiled program as first parameter?

I'm not sure what this should look like in compiletest, maybe a configuration parameter or something?

**Comment by malbarbo** [comment]
> If I understand the runner thing right, specifying something like "bash" or "python" would make cargo run those with the compiled program as first parameter?

Yes. But guess what? The `Config::runtool` options does exactly that! It is used to run valgrind, but I was able to it to run qemu.

Thanks!
